<?php

declare(strict_types=1);

namespace Zenigata\Http\Middleware;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

/**
 * Defines a contract for a middleware dispatcher.
 *
 * Processes the middleware stack up to the final handler,
 * resolving middleware instances as needed.
 */
interface MiddlewareDispatcherInterface
{
    /**
     * Process the middleware pipeline.
     *
     * @param ServerRequestInterface  $request The incoming request.
     * @param RequestHandlerInterface $handler The final request handler.
     * 
     * @return ResponseInterface The response generated by the request handler.
     */
    public function dispatch(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface;

    /**
     * Adds a middleware into the stack.
     *
     * @param MiddlewareInterface|string $middleware Middleware instance, or resolvable string identifier.
     */
    public function addMiddleware(MiddlewareInterface|string $middleware): void;

    /**
     * Returns the registered middleware.
     *
     * @return list<MiddlewareInterface|string> List of middleware instances, or resolvable string identifier.
     */
    public function getMiddleware(): array;
}